<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
/*
 * common module
 *
 * @copyright       XOOPS Project https://xoops.org/
 * @license         GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
 * @package         common
 * @since           1.00
 * @author          luciorota, studiopas
 * @version         svn:$Id$
 */

defined('XOOPS_ROOT_PATH') || die('XOOPS root path not defined');

$modversion['dirname'] = basename(__DIR__);
$modversion['name'] = ucfirst(basename(__DIR__));
$modversion['version'] = '1.0.0-Beta.11';
$modversion['description'] = '';
$modversion['author'] = 'Rota Lucio';
$modversion['url'] = 'http://xoops.org';
$modversion['credits'] = '';

$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2 or later';
$modversion['license_url'] = 'http://www.gnu.org/licenses/gpl-2.0.html';
$modversion['official'] = 0;
$modversion['image'] = 'assets/images/logo.png'; // Path and name of the module’s logo

$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16'] = 'Frameworks/moduleclasses/icons/16'; //'images/icons/16'
$modversion['icons32'] = 'Frameworks/moduleclasses/icons/32'; //'images/icons/32'

$modversion['official'] = false;

include_once XOOPS_ROOT_PATH . "/modules/{$modversion['dirname']}/include/constants.php";

// About stuff
$modversion['module_status'] = 'b11';
$modversion['release_date'] = date('n/d/Y', (filemtime(__FILE__))); //'11/27/2017';

$modversion['developer_lead'] = 'luciorota';
$modversion['developer_website_url'] = 'http://luciorota.altervista.org';
$modversion['developer_website_name'] = 'luciorota.altervista.org';
$modversion['developer_email'] = 'lucio.rota@gmail.com';

$modversion['people']['developers'][] = '';

$modversion['min_xoops'] = '2.5.10';
$modversion['min_php'] = '5.5';
$modversion['min_admin'] = '1.2';
$modversion['min_db'] = array(
    'mysql' => '5.0.7',
    'mysqli' => '5.0.7'
);

// Install, update, unistall
$modversion['onInstall'] = 'include/install.php';
$modversion['onUpdate'] = 'include/uninstall.php'; // IN PROGRESS
$modversion['onUninstall'] = 'include/update.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// Tables created by sql file (without prefix!)
$modversion['tables'][] = "mod_{$modversion['dirname']}_test";
$modversion['tables'][] = "mod_{$modversion['dirname']}_testcategory";




// Help files
$modversion['helpsection'][] = array(
    'name' => 'help1',
    'link' => 'page=help1'
);
$modversion['helpsection'][] = array(
    'name' => 'help2',
    'link' => 'page=help2'
);
$modversion['helpsection'][] = array(
    'name' => 'help3',
    'link' => 'page=help3'
);



// Admin things
$modversion['hasAdmin'] = 1;
$modversion['system_menu'] = 1; // If you want your module has a sub menu in system menu set it to 1
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu']  = 'admin/menu.php';



// Menu things
$modversion['hasMain'] = 1;



// Search
$modversion['hasSearch'] = 0;



// Blocks



// Templates
// Is performing module install/update?
$isModuleAction = @(// action module "system"
        !empty($GLOBALS['xoopsModule']) && 'system' === $GLOBALS['xoopsModule']->getVar('dirname', 'n') && // current dirname
        ($modversion['dirname'] == $_POST['dirname'] || $modversion['dirname'] == $_POST['module']) && // current op
        ('update_ok' === $_POST['op'] || 'install_ok' === $_POST['op'] || 'uninstall_ok' === $_POST['op']) && // current action
        'modulesadmin' === $_POST['fct']);
if ($isModuleAction) {
    include_once(XOOPS_ROOT_PATH . '/class/xoopslists.php');
    $files = XoopsLists::getHtmlListAsArray(__DIR__ . '/templates/');
    $list = array();
    foreach ($files as $file => $name) {
        // The valid file name must be: archivio_.tpl
        if (preg_match("/^{$modversion['dirname']}_(.*)?\.(tpl)$/i", $name, $matches)) {
            if (empty($matches[1]))
                continue;
            $list[] = array('file' => $name, 'type' => 'default', 'description' => $matches[1]);
        }
    }
    $modversion['templates'] = $list;
}



// Module config setting
$modversion['config'] = array();
xoops_load('XoopsEditorHandler');
$editor_handler         = XoopsEditorHandler::getInstance();
$editorList             = array_flip($editor_handler->getList());
$modversion['config'][] = array(
    'name'        => 'editor',
    'title'       => '_MI_COMMON_EDITOR',
    'description' => '_MI_COMMON_EDITOR_DESC',
    'formtype'    => 'select',
    'valuetype'   => 'text',
    'options'     => $editorList,
    'default'     => 'dhtml'
);
$modversion['config'][] = array(
    'name'        => 'GoogleMapsAPIKey',
    'title'       => '_MI_COMMON_GOOGLEMAPSAPIKEY',
    'description' => '_MI_COMMON_GOOGLEMAPSAPIKEY_DESC',
    'formtype'    => 'text',
    'valuetype'   => 'text',
    'default'     => ''
);



// Comments
$modversion['hasComments'] = false;



// Notification
$modversion['hasNotification'] = false;
